[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "cellBiologyFgPC"
version = "0.0.1"

[tool.setuptools.packages.find]
# All the following settings are optional:
where = ["src"]  # ["."] by default

